Fix kernel build with glibc 2.34
In glibc 2.34 was removed reference to '__libc_csu_fini' and  '__libc_csu_init'. Building ended with this error.

/work/2/Lineage17.1/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/../sysroot/usr/lib/crt1.o(.text+0x12): error: undefined reference to '__libc_csu_fini'
/work/2/Lineage17.1/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/../sysroot/usr/lib/crt1.o(.text+0x19): error: undefined reference to '__libc_csu_init'
collect2: error: ld returned 1 exit status

Change-Id: I927af72afe7d73f395fd85f584fcb04082e050dd