build: Drop build-manifest.xml generation
This breaks the build in CP2A:
OSError: [Errno 30] Read-only file system: '.repo/manifests.git/.repo_config.json'
Write to a read-only file system detected. Possible fixes include
1. Generate file directly to out/ which is ReadWrite, #recommend solution
2. BUILD_BROKEN_SRC_DIR_RW_ALLOWLIST := <my/path/1> <my/path/2> #discouraged, subset of source tree will be RW
3. BUILD_BROKEN_SRC_DIR_IS_WRITABLE := true #highly discouraged, entire source tree will be RW

Change-Id: If6d346ab6a1178b3895be25662a507e575a8c6f1